version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: card_marketplace_db
    environment:
      POSTGRES_DB: card_marketplace
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: card_marketplace_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data: