spring.application.name=card-marketplace

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/card_marketplace
spring.datasource.username=${POSTGRES_NAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# oAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# JustTcg
justtcg.api.key=${JUSTTCG_API_KEY}
justtcg.api.base-url=${JUSTTCG_BASE_URL:https://api.justtcg.com/v1}

# Swagger/OpenApi
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Aws
aws.s3.region=${AWS_S3_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}

app.cdn.base-url=${CDN_BASE_URL}
