spring.application.name=card-marketplace

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/card_marketplace
spring.datasource.username=luis
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379