# Swagger/OpenAPI ? dev only, never prod
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# AWS S3 (dev = LocalStack)
aws.s3.endpoint=${AWS_S3_ENDPOINT}
aws.s3.access-key=${AWS_S3_ACCESS_KEY}
aws.s3.secret-key=${AWS_S3_SECRET_KEY}